<footer>
    <div class="jumbotron" style="background-color:#191919;color:#fff;margin-bottom:0px;">
      <div class="container" style="">
        <div class="row">
            <div class="col-md-4">
                Heading
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. 
                
            </div>
            <div class="col-md-4">
                Heading
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. 
                
            </div>
            <div class="col-md-4">
                Heading
                Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
                
            </div>
        </div>
      </div>
    </div>
    <div class="container-fluid" style="background-color:#000;color:#fff">
        <div class="row">
            <div class="col-md-9">
                <p>© <?php echo date('Y'); ?> Company, Inc.</p>
            </div>
            <div class="col-md-3">
                <a href="#">Link 1</a> | 
                <a href="#">Link 2</a> | 
                <a href="#">Link 3</a> | 
                <a href="#">Link 4</a>
            </div>
        </div>
    </div>
</footer>