<div class="row" style="margin-left:0px;margin-right:0px;">
    <div class="col-md-8">
        <div class="logo" style="padding-left:5%;">
            <img src ="<?php echo BASE_PATH; ?>/img/banners/logo.jpg" class="img-responsive">
        </div>
    </div>
    <div class="col-md-4">
        <div class="search-bar" style="padding-top:10%;">
            <form>
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </div>
            </form>
        </div>
    </div>
</div>